on:
  # 每当创建tag时触发发布
  push:
    tags:
      - "v*"
  # 手动触发发布
  workflow_dispatch:

name: publish
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: "14"
          registry-url: https://registry.npmjs.org/
      - run: yarn
      - run: yarn build
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}

  github-release:
    needs: publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: "14"
          registry-url: https://registry.npmjs.org/
      - run: npm i -g github-release-from-changelog
      - run: github-release-from-changelog
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
